"""Initial migration

Revision ID: 66a861c9f537
Revises: 
Create Date: 2025-11-30 22:17:51.411490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a861c9f537'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_index('idx_game_type', ['game_id', 'pick_type'], unique=False)
        batch_op.create_index('idx_result_graded', ['result', 'graded_at'], unique=False)
        batch_op.create_index('idx_user_type_result', ['user_id', 'pick_type', 'result'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_index('idx_user_type_result')
        batch_op.drop_index('idx_result_graded')
        batch_op.drop_index('idx_game_type')

    # ### end Alembic commands ###
